### ISSUE TITLE
Multi-threading issue

### ISSUE THREAD

**Issue by 4gus71n** [cbruegg/ORMLite-RxJava#1]
I'm currently having some issues on my App due RxJava+Ormlite. I'm using Schedulers.io() as the Scheduler, but some times I get some warnings saying that I'm trying to insert already existing rows when using createOrUpdate() and some other weird errors like that. I've been told that this errors may happen because the queries are running on separated threads. Could you update your Readme with an example? I'm curious about which Scheduler would you use.

**Comment by cbruegg** [comment]
Hi, the problem may be that `Schedulers.io()` uses a thread pool rather than a single thread. You should probably use `Schedulers.newThread()` and share that scheduler across your application for accessing the database. I've updated the readme with an example. Hope this helps :-)
